name: CI

on:
  push:
    tags:
    - v*
    branches:
    - master
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v5.0.0
      with:
        version: v1.50.1

  tidy:
    name: go mod tidy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0

    - uses: actions/setup-go@v3.5.0
      with:
        go-version: '^1.17.1'

    - name: Cache
      uses: actions/cache@v3.2.3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: go-tidy-check
      uses: katexochen/go-tidy-check@v1.0.2

  test:
    name: Go ${{ matrix.go-version }} test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version:
        - 1.17.x
        - 1.18.x
        - 1.19.x

    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0

    - name: Setup go
      uses: actions/setup-go@v3.5.0
      with:
        go-version: ${{ matrix.go-version }}

    - name: Cache
      uses: actions/cache@v3.2.3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Test
      run: go test -v -race ./...
